# Generated by Django 5.0.2 on 2024-03-11 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Model",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=50, null=True)),
                ("location", models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                "db_table": "model",
            },
        ),
    ]
