# Generated by Django 4.2.5 on 2024-03-26 09:54

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("services", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Chat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("chat_id", models.CharField(max_length=100)),
                ("chat_name", models.CharField(max_length=100)),
                (
                    "members",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=100), size=None
                    ),
                ),
            ],
            options={
                "db_table": "chat",
            },
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "message_id",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
                ("timestamp", models.DateTimeField()),
                ("content", models.TextField()),
                ("sender_id", models.CharField(max_length=100)),
                (
                    "chat_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="services.chat"
                    ),
                ),
            ],
            options={
                "db_table": "message",
            },
        ),
    ]
