# Generated by Django 5.0.3 on 2024-03-26 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_chat_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='chat_id',
        ),
        migrations.DeleteModel(
            name='Chat',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
    ]
