# Generated by Django 5.0.3 on 2024-03-28 16:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_achievement_blobstorage_chat_contact_event_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blobstorage',
            name='Date',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.physicalattribute'),
        ),
    ]
