# Generated by Django 5.0.3 on 2024-03-26 11:01

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_remove_message_chat_id_delete_chat_delete_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.CharField(max_length=100)),
                ('chat_name', models.CharField(max_length=100)),
                ('members', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), size=None)),
            ],
            options={
                'db_table': 'chat',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('message_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField()),
                ('content', models.TextField()),
                ('sender_id', models.CharField(max_length=100)),
                ('chat_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.chat')),
            ],
            options={
                'db_table': 'message',
            },
        ),
        migrations.DeleteModel(
            name='Model',
        ),
    ]
