# Generated by Django 5.0.3 on 2024-03-28 16:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_alter_blobstorage_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='isverified',
            name='Verified_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='services.verified'),
        ),
    ]
