# Generated by Django 5.0.3 on 2024-03-26 15:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_chat_message_delete_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('achievement', models.CharField(max_length=250, primary_key=True, serialize=False)),
                ('date', models.DateField()),
            ],
            options={
                'db_table': 'achievement',
            },
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('topic', models.CharField(max_length=150, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('description', models.TextField()),
            ],
            options={
                'db_table': 'experience',
            },
        ),
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'model',
            },
        ),
        migrations.CreateModel(
            name='Owns',
            fields=[
                ('chat_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='services.chat')),
            ],
            options={
                'db_table': 'owns',
            },
        ),
        migrations.CreateModel(
            name='Physical_Attribute',
            fields=[
                ('date', models.DateTimeField(primary_key=True, serialize=False)),
                ('height', models.IntegerField()),
                ('speed', models.IntegerField()),
                ('fat_mass', models.DecimalField(decimal_places=2, max_digits=4)),
                ('muscle_mass', models.DecimalField(decimal_places=2, max_digits=4)),
                ('weight', models.DecimalField(decimal_places=1, max_digits=4)),
            ],
            options={
                'db_table': 'physical_attribute',
            },
        ),
    ]
