from django.db import models

class Scout(models.Model):
    User_ID = models.CharField(primary_key=True, max_length=16)
    #Org_Name = models.ForeignKey('Organization', on_delete=models.CASCADE)
    Hometown_CHOICES = [
        ('Amnat Charoen', 'Amnat Charoen'),
        ('Ang Thong', 'Ang Thong'),
        ('Bangkok', 'Bangkok'),
        ('Bueng Kan', 'Bueng Kan'),
        ('Buri Ram', 'Buri Ram'),
        ('Chachoengsao', 'Chachoengsao'),
        ('Chai Nat', 'Chai Nat'),
        ('Chaiyaphum', 'Chaiyaphum'),
        ('Chanthaburi', 'Chanthaburi'),
        ('Chiang Mai', 'Chiang Mai'),
        ('Chiang Rai', 'Chiang Rai'),
        ('Chon Buri', 'Chon Buri'),
        ('Chumphon', 'Chumphon'),
        ('Kalasin', 'Kalasin'),
        ('Kamphaeng Phet', 'Kamphaeng Phet'),
        ('Kanchanaburi', 'Kanchanaburi'),
        ('Khon Kaen', 'Khon Kaen'),
        ('Krabi', 'Krabi'),
        ('Lampang', 'Lampang'),
        ('Lamphun', 'Lamphun'),
        ('Loei', 'Loei'),
        ('Lopburi', 'Lopburi'),
        ('Mae Hong Son', 'Mae Hong Son'),
        ('Maha Sarakham', 'Maha Sarakham'),
        ('Mukdahan', 'Mukdahan'),
        ('Nakhon Nayok', 'Nakhon Nayok'),
        ('Nakhon Pathom', 'Nakhon Pathom'),
        ('Nakhon Phanom', 'Nakhon Phanom'),
        ('Nakhon Ratchasima', 'Nakhon Ratchasima'),
        ('Nakhon Sawan', 'Nakhon Sawan'),
        ('Nakhon Si Thammarat', 'Nakhon Si Thammarat'),
        ('Nan', 'Nan'),
        ('Narathiwat', 'Narathiwat'),
        ('Nong Bua Lam Phu', 'Nong Bua Lam Phu'),
        ('Nong Khai', 'Nong Khai'),
        ('Nonthaburi', 'Nonthaburi'),
        ('Pathum Thani', 'Pathum Thani'),
        ('Pattani', 'Pattani'),
        ('Phangnga', 'Phangnga'),
        ('Phatthalung', 'Phatthalung'),
        ('Phayao', 'Phayao'),
        ('Phetchabun', 'Phetchabun'),
        ('Phetchaburi', 'Phetchaburi'),
        ('Phichit', 'Phichit'),
        ('Phitsanulok', 'Phitsanulok'),
        ('Phra Nakhon Si Ayutthaya', 'Phra Nakhon Si Ayutthaya'),
        ('Phrae', 'Phrae'),
        ('Phuket', 'Phuket'),
        ('Prachin Buri', 'Prachin Buri'),
        ('Prachuap Khiri Khan', 'Prachuap Khiri Khan'),
        ('Ranong', 'Ranong'),
        ('Ratchaburi', 'Ratchaburi'),
        ('Rayong', 'Rayong'),
        ('Roi Et', 'Roi Et'),
        ('Sa Kaeo', 'Sa Kaeo'),
        ('Sakon Nakhon', 'Sakon Nakhon'),
        ('Samut Prakan', 'Samut Prakan'),
        ('Samut Sakhon', 'Samut Sakhon'),
        ('Samut Songkhram', 'Samut Songkhram'),
        ('Saraburi', 'Saraburi'),
        ('Satun', 'Satun'),
        ('Sing Buri', 'Sing Buri'),
        ('Sisaket', 'Sisaket'),
        ('Songkhla', 'Songkhla'),
        ('Sukhothai', 'Sukhothai'),
        ('Suphan Buri', 'Suphan Buri'),
        ('Surat Thani', 'Surat Thani'),
        ('Surin', 'Surin'),
        ('Tak', 'Tak'),
        ('Trang', 'Trang'),
        ('Trat', 'Trat'),
        ('Ubon Ratchathani', 'Ubon Ratchathani'),
        ('Udon Thani', 'Udon Thani'),
        ('Uthai Thani', 'Uthai Thani'),
        ('Uttaradit', 'Uttaradit'),
        ('Yala', 'Yala'),
        ('Yasothon', 'Yasothon'),
    ]
    Hometown = models.CharField(max_length=30, choices=Hometown_CHOICES)
    Birthdate = models.DateField()
    Age = models.IntegerField()

    class Meta:
        db_table = "scout"

    def __str__(self):
        return f"Scout {self.User_ID}"